build_input_shape: !!python/tuple
- null
- 128
dtype: float32
layers:
- class_name: InputLayer
  config:
    batch_shape: !!python/tuple
    - null
    - 128
    dtype: float32
    name: input_layer
    sparse: false
  module: keras.layers
  registered_name: null
- build_config:
    input_shape: !!python/tuple
    - null
    - 128
  class_name: Embedding
  config:
    activity_regularizer: null
    dtype: float32
    embeddings_constraint: null
    embeddings_initializer:
      class_name: RandomUniform
      config:
        maxval: 0.05
        minval: -0.05
        seed: null
      module: keras.initializers
      registered_name: null
    embeddings_regularizer: null
    input_dim: 94
    mask_zero: false
    name: embedding
    output_dim: 64
    trainable: true
  module: keras.layers
  registered_name: null
- build_config:
    input_shape: !!python/tuple
    - null
    - 128
    - 64
  class_name: GlobalAveragePooling1D
  config:
    data_format: channels_last
    dtype: float32
    keepdims: false
    name: global_average_pooling1d
    trainable: true
  module: keras.layers
  registered_name: null
- build_config:
    input_shape: !!python/tuple
    - null
    - 64
  class_name: Dense
  config:
    activation: relu
    bias_constraint: null
    bias_initializer:
      class_name: Zeros
      config: {}
      module: keras.initializers
      registered_name: null
    bias_regularizer: null
    dtype: float32
    kernel_constraint: null
    kernel_initializer:
      class_name: GlorotUniform
      config:
        seed: null
      module: keras.initializers
      registered_name: null
    kernel_regularizer: null
    name: dense
    trainable: true
    units: 64
    use_bias: true
  module: keras.layers
  registered_name: null
- build_config:
    input_shape: !!python/tuple
    - null
    - 64
  class_name: Dense
  config:
    activation: sigmoid
    bias_constraint: null
    bias_initializer:
      class_name: Zeros
      config: {}
      module: keras.initializers
      registered_name: null
    bias_regularizer: null
    dtype: float32
    kernel_constraint: null
    kernel_initializer:
      class_name: GlorotUniform
      config:
        seed: null
      module: keras.initializers
      registered_name: null
    kernel_regularizer: null
    name: dense_1
    trainable: true
    units: 1
    use_bias: true
  module: keras.layers
  registered_name: null
name: sequential
trainable: true
